# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Change
                                 A QGIS plugin
 Change
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-02-06
        copyright            : (C) 2019 by jb
        email                : jb
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Change class from file Change.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Change import Change
    return Change(iface)
